### ISSUE TITLE
ESP8266 reboots at the start of calbration.

### ISSUE THREAD

**Issue by Bodmer** [achillhasler/TFT_eTouch#1]
The calibrate sketch puts marker on the screen then the ESP8266 reboots on the watchdog.

**Comment by achillhasler** [comment]
Thank you for testing. I dont have a ESP8266 and can't test that.
Does it reboot also with
         touch.getCalibration(calibation, 11); (This show 4 full marker)

Does the ESP8266 also reboot when we draw outsite the Display (without Touch code)?
try: tft.fillCircle(4, 4, 10, TFT_GREEN);
  or tft.drawCircle(4, 4, 10, TFT_BLUE);
  or tft.drawCircle(tft.width() - 5, tft.height() - 5, 10, TFT_BLUE);
  or tft.fillCircle(tft.width() - 5, tft.height() - 5, 10, TFT_GREEN);
I asume in my lib that this works without any problems. ESP32 with RPI_ILI9486_DRIVER has no problem.

Does the raw test working well?

**Comment by achillhasler** [comment]
In Version 0.6.0 ESP8266 work as expected.
