### ISSUE TITLE
TFT_eTouch and SD card

### ISSUE THREAD

**Issue by YuryKushnir** [achillhasler/TFT_eTouch#10]
Hi
I tried your TFT_eTouch library with ESP32 and ILI9488.
Everything works fine.
But if I add SD module with card to the schematic and add SD.H to the code
and add SD card initialization:
SD.begin(5)
Touchscreen doesn't work.
If I physically remove SD module by hot, touchscreen begin works
How can I use TouchScreen and SD together?

Best rerards
Yury

**Comment by achillhasler** [comment]
Hi Yury,
i have added some code from TFT_eSPI/examples/Generic/ESP32_SDCard_jepg.ino to my raw test.
#include <SD.h> // at the top
// in begin after   while (!Serial) ; // wait for Arduino Serial Monitor

#ifdef SD_DEMO
  digitalWrite( 5, HIGH); // SD card chips select, must use GPIO 5 (ESP32 SS)

  if (!SD.begin(5, tft.getSPIinstance())) {
    Serial.println("Card Mount Failed");
    return;
  }
  uint8_t cardType = SD.cardType();

  if (cardType == CARD_NONE) {
    Serial.println("No SD card attached");
    return;
  }

  Serial.print("SD Card Type: ");
  if (cardType == CARD_MMC) {
    Serial.println("MMC");
  } else if (cardType == CARD_SD) {
    Serial.println("SDSC");
  } else if (cardType == CARD_SDHC) {
    Serial.println("SDHC");
  } else {
    Serial.println("UNKNOWN");
  }

  uint64_t cardSize = SD.cardSize() / (1024 * 1024);
  Serial.printf("SD Card Size: %lluMB\n", cardSize);
#endif

The output in TERMINAL
Measure Bits: 12, RawValidMin: 24, RawValidMax: 4000
SD Card Type: SDHC  >> Card is mounted <<
SD Card Size: 7699MB
x,y,z1,z2,rz = 2731,1314,780,2781,569 >>when touching display i get results <<
x,y,z1,z2,rz = 2721,1324,818,2712,512
...

SD card works with TFT_eSPI (ILI9341_DRIVER) and TFT_eTouch (bud i have only tested the SD.begin() no r/w ops)
Hope this helps
ciao Achill

**Comment by YuryKushnir** [comment]
Hi Achill
I repeated your experiment with RAW test
My ESP32 and ILI9488 connections
MISO 19
MOSI 23
SCK 18
TFT_CS 15
Touch_CS 25
T_IRQ 26
SD_CS 5

I added SD.H at the top and if (!SD.begin(5, tft.getSPIinstance())) {.....
after " in begin after while (!Serial) ;".
Result:
- SD Ok!
- touch does not work
- if I remove SDmodule - system can read touch coordinates.

I cheked https://github.com/achillhasler/TFT_eTouch/tree/master/examples/generic/calibrate test with SD
Same result.

I did many experiments
What I found
First: ILI9488 is not sensitive to CS_Touch. You can connect  CS_Touch to any leg, even not like in the program, you can disable (hang in the air) CS_touch
In all these cases, touch will work stable.
But if you install SDmodule with SD - touch will stop working.
- Is your ILI9341 sensitive to CS_Touch connection? 

Second: if after each work with SD write
pinMode(19,OUTPUT); // MISO pin
digitalWrite(19,LOW);
Touch will work, but unstable. This is also true for RAW test
- What do you think about setting MISO to LOW for touch to work?

I saw that we have only one difference: you use ILI9341, and I use ILI9488.
I think ILI9488 has a bug in the circuit because it not sensitive to CS_Touch.
I will buy ILI9341 and report the result.
May you test RAW with ILI9488?

**Comment by achillhasler** [comment]
Hi Yury,
if i understand that right (ILI9488 is not sensitive to CS_Touch) touch pin has no function, eg. touch chip is allways selected.
I asume touch chip, ili9488 and sd are on the same spi-bus (share VSPI MISO 19, MOSI 23, SCK 18) with different cs pins. 
When ili9488 and touch chip works well together (without SD) put these two chips to HSPI (MISO 12, MOSI 13, SCK 14) and let SD on VSPI maybe this works. (call SD.begin(5) not SD.begin(5, tft.getSPIinstance()))
Is your ILI9341 sensitive to CS_Touch connection?
This question make no sense, ILI9341 (or ili9488) and touch chip on your display bord are independend, also SD-card is independend. When CS from ili goes low, then miso, mosi and sck of the ili are activated, and the cpu speak with the ili chip. The
other two chips stay inactive. If two chips on the spi bus has a CS LOW, spi bus is corrupt. Because two chips recive data from the cpu or want send data to the cpu MISO pin.
What do you think about setting MISO to LOW for touch to work?
make no sense for me, Arduino configure the 3 spi pins to spi mode on every SPI call. (MISO means Master IN Slave OUT)
CPU is the Master, and MISO must be an INPUT on CPU or an OUTPUT on the slave.
I saw that we have only one difference: you use ILI9341, and I use ILI9488. 
other difference, i dont use T_IRQ 26 in my test.
I will buy ILI9341 and report the result.
bud ILI9341 has only 240*320 reso not 320*480 like ILI9488. Try first ILI9488 and touch on HSPI, SD on VSPI.
May you test RAW with ILI9488?
I cant make this because i dont have one. I have a ILI9486 (reso 320*480) made for rasperrypi with a stupid spi interface. (there are 4 additionals chips 2 serial to paralell chips and some logic)

**Comment by YuryKushnir** [comment]
Hi Achilles!! BINGO! !!!!!!! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Thank you very much !!!!
I moved Touch to "SECOND_SPI_PORT" and everything works
I Found in your RAW :
#define SECOND_SPI_PORT

#ifdef SECOND_SPI_PORT
#define TFT_ETOUCH_SCK 14
#define TFT_ETOUCH_MISO 12
#define TFT_ETOUCH_MOSI 13
SPIClass hSPI(HSPI);
#endif
I uncommented it and everything started working
I checked for SD: initialisation, list dir, read, write, delete files - Touch is OK !!!
Thank you very much !!!!

Before try eTouch.h I used Touch.h of TFT_eSPI
..\libraries\TFT_eSPI\Extensions\Touch.h
All settings in User_Setup.h is correct.
I tryed move touch functional to HSPI and use Touch.h 
But touch no work.
I have never used HSPI/VSPI and have no experience. Maybe there is a bug in my code or Touch.h library can't work with HSPI?
I have attached my code.
Сould you please see what is wrong here?
--------------------------------
#include "FS.h"

#include <SPI.h>
#include <TFT_eSPI.h> 

//  Touch
#define HSPI_MISO 12
#define HSPI_MOSI 13
#define HSPI_SCLK 14
#define HSPI_SS   25

// TFT
#define VSPI_MISO 19
#define VSPI_MOSI 23
#define VSPI_SCLK 18
#define VSPI_SS   15


TFT_eSPI tft = TFT_eSPI(); // Invoke custom library

#define CALIBRATION_FILE "/TouchCalData2"

char buf[50];

uint16_t t_x = 0, t_y = 0; // To store the touch coordinates
int ii=0; 

//uninitialized pointers to SPI objects
SPIClass *vspi = NULL;
SPIClass *hspi = NULL;

void setup() {

//initialize two instances of the SPIClass attached to VSPI and HSPI respectively
vspi = new SPIClass(VSPI);
hspi = new SPIClass(HSPI);

//alternatively route through GPIO pins of your choice
vspi->begin(VSPI_SCLK, VSPI_MISO, VSPI_MOSI, VSPI_SS);  //SCLK, MISO, MOSI, SS

//alternatively route through GPIO pins
hspi->begin(HSPI_SCLK, HSPI_MISO, HSPI_MOSI, HSPI_SS);  //SCLK, MISO, MOSI, SS

//set up slave select pins as outputs as the Arduino API
//doesn't handle automatically pulling SS low
pinMode(vspi->pinSS(), OUTPUT);  //VSPI SS
pinMode(hspi->pinSS(), OUTPUT);  //HSPI SS


Serial.begin(115200); 

tft.begin();

if (!SPIFFS.begin()) {  Serial.println("Formating file system");   SPIFFS.format(); SPIFFS.begin(); }
touch_calibrate(0);  

tft.fillScreen(TFT_BLACK);

 Serial.println("START");
 
}

//---------------------------------------------------------------

void loop() {
  tft.setCursor(20, 60);
              sprintf(buf,"---  I= %4i", ii++);
              if(ii>1000) ii=0;
              tft.print(buf);

bool pressed = tft.getTouch(&t_x, &t_y);
if( pressed) {
              sprintf(buf,"X=%3i  Y=%3i  ",t_x,t_y);
              Serial.printf("%s\n",buf);

              tft.setCursor(20, 20);
              tft.print(buf);
                }
}

//-----------------------------------------------------------------------------------------

void touch_calibrate(short flag) 
{
   uint16_t calData[5];
  uint8_t calDataOK = 0;
  File f;

  if (SPIFFS.exists(CALIBRATION_FILE)) {  
              if (flag)  SPIFFS.remove(CALIBRATION_FILE); 
                      else 
                            {     f = SPIFFS.open(CALIBRATION_FILE, "r");
                                  if (f) { 
                                    if (f.readBytes((char *)calData, 14) == 14) { calDataOK = 1; }
                                                                             else    f.close();
                                        }  // --- END if(f)
                            }  
  } 

  if (calDataOK && !flag) { 
    tft.setTouch(calData);
  } 
  else {  
    tft.fillScreen(TFT_BLACK);
    tft.setCursor(20, 0);
    tft.setTextFont(2);
    tft.setTextColor(TFT_WHITE, TFT_BLACK);

    tft.println("Touch corners as indicated");
       
    tft.setTextFont(2);
    tft.println();

    tft.calibrateTouch(calData, TFT_MAGENTA, TFT_BLACK, 15);

    // store data
    f = SPIFFS.open(CALIBRATION_FILE, "w");
    if (f) {
      tft.setTextColor(TFT_GREEN, TFT_BLACK);
      tft.println("Calibration complete!");
      f.write((const unsigned char *)calData, 14);
      f.close();
     
    }  // ------ END if   save file
  }   // ------ END need cal
}  // ----------------- END Touch_calibrate -------------------------



--------------------------------
Thanks again for your help
Best regards , Yury

**Comment by achillhasler** [comment]
Hi Yury,
nice that eTouch works for you with two differnt spi ports. SD use default SPI (VSPI) eSPI and eTouch use HSPI.

The line
TFT_eSPI tft = TFT_eSPI(); // Invoke custom library
will use VSPI without defining USE_HSPI_PORT
When you define USE_HSPI_PORT in your build environment, then eSPI will use the HSPI port. (i dont have tryed that, but might work) see also TFT_eSPI/Processors/TFT_eSPI_ESP32.h for more informations.
Bud this is a eSPI issue when not working for you, pls make a issue in eSPI repo then.

**Comment by YuryKushnir** [comment]
Hi, Achill
I tried to run the code with TFT_eSPI.h and Touch.h as I wrote before.
I want to use it because my big project is built with it.
You suggest to define USE_HSPI_PORT...
I did:
Uncommented #define USE_HSPI_PORT in User_setup.h
Result - TFT works, Touch doesn't.
I think Touch.h can't understand that it needs to use HSPI pins and work with HSPI for touch input.
I broke my head trying to make VSPI and HSPI work
I read many articles but still couldn't find a solution.
I think I need to create two objects:
1) for TFT VSPI ---- TFT_eSPI        tft = TFT_eSPI();
2) for Touch HSPI  ????
And assign HSPI for Touch object.
And init like tft.init() but for touch .....
But how can I implement it?
Please check my code, what is the problem?

Best regards
Yury

------------------------Plese Help---------------------------------------------------

#include "FS.h"
#include <SPI.h>
#include <TFT_eSPI.h>

//  Touch
#define HSPI_MISO 12
#define HSPI_MOSI 13
#define HSPI_SCLK 14
#define HSPI_SS   25

// TFT
#define VSPI_MISO 19
#define VSPI_MOSI 23
#define VSPI_SCLK 18
#define VSPI_SS   15

SPIClass hSPI(HSPI);
SPIClass vSPI(VSPI);

TFT_eSPI tft = TFT_eSPI(); // Invoke custom library
TFT_eSPI touch = TFT_eSPI(); 

#define CALIBRATION_FILE "/TouchCalData2"

char buf[50];
int ii=0;

//uninitialized pointers to SPI objects
//SPIClass *vspi = NULL;
//SPIClass *hspi = NULL;

void setup() {
//initialize two instances of the SPIClass attached to VSPI and HSPI respectively
//vspi = new SPIClass(VSPI);
//hspi = new SPIClass(HSPI);

//alternatively route through GPIO pins of your choice
//vspi->begin(VSPI_SCLK, VSPI_MISO, VSPI_MOSI, VSPI_SS);  //SCLK, MISO, MOSI, SS
vSPI.begin(VSPI_SCLK, VSPI_MISO, VSPI_MOSI, VSPI_SS);  //SCLK, MISO, MOSI, SS


//alternatively route through GPIO pins
//hspi->begin(HSPI_SCLK, HSPI_MISO, HSPI_MOSI, HSPI_SS);  //SCLK, MISO, MOSI, SS
hSPI.begin(HSPI_SCLK, HSPI_MISO, HSPI_MOSI, HSPI_SS);  //SCLK, MISO, MOSI, SS


//set up slave select pins as outputs as the Arduino API
//doesn't handle automatically pulling SS low
pinMode(VSPI_SS, OUTPUT);  //VSPI SS
pinMode(HSPI_SS, OUTPUT);  //HSPI SS

Serial.begin(115200); 

tft.init(); 
tft.setRotation(0); 

 if (!SPIFFS.begin()) {  Serial.println("Formating file system");   SPIFFS.format(); SPIFFS.begin(); }
touch_calibrate(0); 

tft.fillScreen(TFT_BLACK);
tft.setTextSize(3);
  
} // -------------------------------------------------------

void loop() {
 uint16_t t_x = 0, t_y = 0; // To store the touch coordinates
 int j=0;

              tft.setCursor(20, 60);
              sprintf(buf," I= %4i", ii);
              ii++;
              if(ii>1000) ii=0;
              tft.print(buf);
 
bool pressed = touch.getTouch(&t_x, &t_y);

if( pressed) {
              sprintf(buf,"X=%3i  Y=%3i   J=%i",t_x,t_y,j++);
              Serial.printf("%s\n",buf);

              tft.setCursor(20, 20);
              tft.print(buf);
               }
} // end loop




//-----------------------------------------------------------------------------------------

void touch_calibrate(short flag) 
{
  // int i=0,ii=0;
  uint16_t calData[5];
  uint8_t calDataOK = 0;
  File f;

  if (SPIFFS.exists(CALIBRATION_FILE)) { 
              if (flag)  SPIFFS.remove(CALIBRATION_FILE); 
                      else  
                            {     f = SPIFFS.open(CALIBRATION_FILE, "r");
                                  if (f) {
                                    if (f.readBytes((char *)calData, 14) == 14)  calDataOK = 1;
                                    f.close();
                                        }  // --- END if(f)
                            }  
  } 
  if (calDataOK && !flag) { 
    tft.setTouch(calData);
  } 
  else {
    tft.fillScreen(TFT_BLACK);
    tft.setCursor(20, 0);
    tft.setTextFont(2);
    tft.setTextColor(TFT_WHITE, TFT_BLACK);
    tft.println("Touch corners as indicated");
    tft.setTextFont(2);
    tft.println();
    tft.calibrateTouch(calData, TFT_MAGENTA, TFT_BLACK, 15);
    // store data
    f = SPIFFS.open(CALIBRATION_FILE, "w");
     Serial.println(f);
    if (f) {
      tft.setTextColor(TFT_GREEN, TFT_BLACK);
      tft.println("Calibration complete!");
      f.write((const unsigned char *)calData, 14);
      f.close();
     
    }  // ------ END if   
  }   // ------ END 
}  // ----------------- END Touch_calibrate -------------------------
//-------------------------------------------------

**Comment by YuryKushnir** [comment]
Hi Achill
I WON!!!!!
Thanks for your help!!!
What did I do?
Used lib -> TFT_eSPI + Touch .h + SD.h
TFT & touch -> VSPI
SD -> HSPI
Normally HSPI uses pin 12 for MISO.
If I connect SD MISO to 12 ESP32 goes into constant reboot no matter what code is in ESP32 (even Blink.h)
I move SD MISO to 17 . 
And ALL is work THANKS
--------------------------------------------------------------------
#include "FS.h"
#include "SD.h"
#include <SPI.h>
#include <TFT_eSPI_Y.h>

//  SD
#define HSPI_MISO 17
#define HSPI_MOSI 13
#define HSPI_SCLK 14
#define HSPI_SS   5

// TFT
#define VSPI_MISO 19
#define VSPI_MOSI 23
#define VSPI_SCLK 18
#define VSPI_SS   15

SPIClass hSPI(HSPI);

TFT_eSPI tft = TFT_eSPI(); // Invoke custom library

#define CALIBRATION_FILE "/TouchCalData2"

uint64_t cardSize;
uint8_t cardType;


int ii=0,j=0,i;

#define F_TXT "/txt_bkp"
#define F_ARRAY "/arr_bkp"
#define F_STR "/str_bkp"

int m[5]={0,1,2,3,4};
char buf[50]="123456789012345678901234567890";

struct {
        int a[2] = {32,32}; // высота кнопки
        int b[2] = {2,4}; // количество кнопок
        char *c[5][4] = {{"<-","->","r","h"},{"Left","1:1","Graf","Right"},{"Left","6-mnt","Graf","Right"},{"Left","3-mnt","Graf","Right"},{"Left","1-mnt","Graf","Right"}};
        short d =1; // масштаб вывода графика:  весь, полгода, 3 месяца, месяц меняется  от 1 до 4, см char *key_gr_text[5][4]
} Btn;

SPIClass *hspi = NULL;

void setup() {

hspi = new SPIClass(HSPI);
hSPI.begin(HSPI_SCLK, HSPI_MISO, HSPI_MOSI, HSPI_SS);  //SCLK, MISO, MOSI, SS

Serial.begin(115200); 

tft.init(); 
tft.setRotation(0); 

 if (!SPIFFS.begin()) {  Serial.println("Formating file system");   SPIFFS.format(); SPIFFS.begin(); }
touch_calibrate(0); 

tft.fillScreen(TFT_BLACK);
tft.setTextSize(3);

//=============================================================================================
if(!SD.begin(5,hSPI))     Serial.println("NO SD Card");

cardType = SD.cardType();
if(cardType == CARD_NONE) Serial.println("No SD card attached");   
Serial.print("SD Card Type: ");
if(cardType == CARD_MMC) Serial.println("MMC");
if(cardType == CARD_SD)  Serial.println("SDSC");
if(cardType == CARD_SDHC) Serial.println("SDHC");

cardSize = SD.cardSize() / (1024 * 1024);
Serial.printf("SD Card Size: %lluMB\n\n", cardSize);
//=============================================================================================



  
} // -------------------------------------------------------

void loop() {
 uint16_t t_x = 0, t_y = 0; // To store the touch coordinates


              tft.setCursor(20, 60);
              sprintf(buf," I= %4i", ii);
              ii++;
              if(ii>1000) ii=0;
              tft.print(buf);
 
bool pressed = tft.getTouch(&t_x, &t_y);

if( pressed) {
              sprintf(buf,"X=%3i  Y=%3i   J=%i",t_x,t_y,j++);
              Serial.printf("%s\n",buf);
              tft.setCursor(20, 20);
              tft.print(buf);
          
              if (j>10) { Print_SD(); j=0; }
               }
} // end loop

//-----------------------------------------------------------------------------------
void Print_SD(){
//  =====================  STRING 
Serial.printf("\nBufsave: %s   sizeofBuf= %i    sizeofM= %i\n", buf,sizeof(buf),sizeof(m));

Serial.printf("Buf: %s\n", buf);
Write_File(SD, F_TXT,(const unsigned char *) buf, sizeof(buf));

sprintf(buf,"hhhh");
Serial.printf("Changed: %s\n", buf);

Read_File(SD, F_TXT,( unsigned char *) buf);
Serial.printf("Reader from file: %s\n", buf);


//  ===================== ARRAY

Serial.printf("\n\nsizeofM= %i\n M= ", sizeof(m));
for(i=0;i<5;i++) Serial.printf("%i  ", m[i]);
Serial.printf("\n"); 

Write_File(SD, F_ARRAY,(const unsigned char *) m, sizeof(m));

Serial.printf("\nChange M\n M= ", sizeof(m));
for(i=0;i<5;i++) { m[i]=8; Serial.printf("%i  ", m[i]);}
Serial.printf("\n"); 

Read_File(SD, F_ARRAY,( unsigned char *) m);
Serial.printf("\nRead\n M= ");
for(i=0;i<5;i++) Serial.printf("%i  ", m[i]);
Serial.printf("\n"); 


//  ===================== STRUCT
Serial.printf("Исходная стуктура\n A=%i A=%i\n",Btn.a[0],Btn.a[1]);
Serial.printf(" B=%i B=%i\n",Btn.b[0],Btn.b[1]);
for(j=0;j<5;j++){
  for (i=0;i<4;i++)  Serial.printf("%s  ",Btn.c[j][i]);
  Serial.println(" ");
}
Serial.printf("D=%i\n",Btn.d);


Write_File(SD, F_STR,(const unsigned char *) &Btn, sizeof(Btn));

Btn.a[0]=Btn.a[1]=Btn.b[0]=Btn.b[1]=Btn.d=555;
Serial.printf("\n\nИзменения \n A=%i A=%i\n",Btn.a[0],Btn.a[1]);
Serial.printf(" B=%i B=%i\n\n",Btn.b[0],Btn.b[1]);


Read_File(SD, F_STR,( unsigned char *) &Btn);

Serial.printf("Считали\n A=%i A=%i\n",Btn.a[0],Btn.a[1]);
Serial.printf(" B=%i B=%i\n",Btn.b[0],Btn.b[1]);
for(j=0;j<5;j++){
  for (i=0;i<4;i++)  Serial.printf("%s  ",Btn.c[j][i]);
  Serial.println(" ");
}
Serial.printf("D=%i\n",Btn.d);
//  ===================== СТРУКТУРА 


listDir(SD, "/", 0);

Serial.println("\n DEL Files\n");
SD.remove(F_TXT);
SD.remove(F_ARRAY);
SD.remove(F_STR);

listDir(SD, "/", 0);

  
}


//-------------------------------------------------------------------------
//------------------------------------------------------------------------------------------
void Write_File(fs::FS &fs, const char * path, const unsigned char * bufsave, unsigned int len){
    File file = fs.open(path, FILE_WRITE);
    if(!file){ Serial.println("Failed to open file for writing"); return;   }
    file.write(bufsave, len);
    file.close();
}

void Read_File(fs::FS &fs, const char * path,  unsigned char * bufsave){
    File file = fs.open(path, FILE_READ);
    if(!file){ Serial.println("Failed to open file for Read"); return;   }
    file.read((unsigned char *)bufsave, file.size());
    file.close();
}


//------------------------------------------------------------------------------------------

void listDir(fs::FS &fs, const char * dirname, uint8_t levels){
    Serial.printf("Listing directory: %s\n", dirname);

    File root = fs.open(dirname);
    if(!root){
        Serial.println("Failed to open directory");
        return;
    }
    if(!root.isDirectory()){
        Serial.println("Not a directory");
        return;
    }

    File file = root.openNextFile();
    while(file){
        if(file.isDirectory()){
            Serial.print("  DIR : ");
            Serial.println(file.name());
            if(levels){
                listDir(fs, file.path(), levels -1);
            }
        } else {
            Serial.print("  FILE: ");
            Serial.print(file.name());
            Serial.print("  SIZE: ");
            Serial.println(file.size());
        }
        file = root.openNextFile();
    }
}

//------------------------------------------------------------------------------------------




//-----------------------------------------------------------------------------------------

void touch_calibrate(short flag) 
{
  // int i=0,ii=0;
  uint16_t calData[5];
  uint8_t calDataOK = 0;
  File f;

  if (SPIFFS.exists(CALIBRATION_FILE)) { 
              if (flag)  SPIFFS.remove(CALIBRATION_FILE); 
                      else  
                            {     f = SPIFFS.open(CALIBRATION_FILE, "r");
                                  if (f) {
                                    if (f.readBytes((char *)calData, 14) == 14)  calDataOK = 1;
                                    f.close();
                                        }  // --- END if(f)
                            }  
  } 
  if (calDataOK && !flag) { 
    tft.setTouch(calData);
  } 
  else {
    tft.fillScreen(TFT_BLACK);
    tft.setCursor(20, 0);
    tft.setTextFont(2);
    tft.setTextColor(TFT_WHITE, TFT_BLACK);
    tft.println("Touch corners as indicated");
    tft.setTextFont(2);
    tft.println();
    tft.calibrateTouch(calData, TFT_MAGENTA, TFT_BLACK, 15);
    // store data
    f = SPIFFS.open(CALIBRATION_FILE, "w");
     Serial.println(f);
    if (f) {
      tft.setTextColor(TFT_GREEN, TFT_BLACK);
      tft.println("Calibration complete!");
      f.write((const unsigned char *)calData, 14);
      f.close();
     
    }  // ------ END if   
  }   // ------ END 
}  // ----------------- END Touch_calibrate -------------------------
//-------------------------------------------------
